FROM jhonatans01/python-dlib-opencv

WORKDIR /Face-Studio

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD ["sh", "-c", "streamlit run --server.port $PORT app.py"] 